Magazine/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.views.generic import TemplateView

handler404 = 'multiclub.views.page_not_found'

urlpatterns = [
    path('', include('multiclub.urls')),
    path('group/<slug:slug>/', include('multiclub.urls',namespace='posts2')),
    path("admin/", admin.site.urls),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('',include('api.urls')),
    path(
        'redoc/',
        TemplateView.as_view(template_name='redoc.html'),
        name='redoc'
    ),
    # path('auth/', include('djoser.urls')),
    # path('auth/', include('djoser.urls.jwt')),

]

api/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views as views_token
from rest_framework.routers import SimpleRouter, DefaultRouter
from . import views
from .views import *

app_name = 'api'

router = DefaultRouter()
router.register('posts', PostViewSet, basename='posts')
router.register('group', GroupViewSet, basename='group')
router.register('follow', FollowViewSet, basename='follow')
comments_router = DefaultRouter()
comments_router.register('comments', CommentViewSet, basename='comments')

urlpatterns = [
    path('api/v1/', include('djoser.urls')),
    path('api/v1/', include('djoser.urls.jwt')),
    # path('api/v1/api-token-auth/', views_token.obtain_auth_token),
    path('api/v1/', include(router.urls)),
    path('api/v1/<int:post_id>/', include(comments_router.urls)),

]

multiclub/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import SimpleRouter

from .views import *

app_name = 'social'

urlpatterns = [
    path('', views.index, name='main'),
    path('group/<slug:slug>/',views.group_posts, name='group'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create_post/', views.new_post, name='create'),
    path('posts/<int:post_id>/edit', views.update_post, name='update'),
    path('posts/<int:post_id>/del', views.delete_post, name='delete'),
    path('posts/<int:post_id>/comment', views.comment, name='comment'),
    path('profile/<str:username>/follow', views.follow, name='follow'),
    path('posts/<int:post_id>/like', views.like_post, name='like'),
    path('subscribe/', views.sub, name='sub'),
    path('posts/tags/<str:tag_name>', views.post_tags, name='tag'),
    path('settings/<str:username>/', views.settings_user, name='settings'),
    path('settings/<str:username>/del', views.delete_image, name='del_image'),
    path('comment/<int:com_id>/del', views.delete_com, name='com_del'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

users/urls.py
from django.contrib.auth.views import (
    LogoutView, LoginView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from django.urls import path
from . import views
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done'),
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<slug:uidb64>/<slug:token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

multiclub/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Tags(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class UserSet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    avatar = models.ImageField('avatar', upload_to='avatar/')


class Post(models.Model):
    title = models.CharField(max_length=200, null=False)
    text = models.CharField(max_length=5000)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    group = models.ForeignKey('Group', blank=True, null=True, related_name='groups', on_delete=models.CASCADE)
    image = models.ImageField('Картинка', upload_to='posts/', blank=True)
    tags = models.ManyToManyField(Tags, through='PostTags', blank=True)


class Group(models.Model):
    title = models.CharField(max_length=500)
    slug = models.CharField(max_length=500)
    description = models.CharField(max_length=500)

    def __str__(self):
        return self.slug


class Comment(models.Model):
    com_date = models.DateTimeField(auto_now_add=True)
    com_author = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='posts', on_delete=models.CASCADE)
    com_text = models.CharField(max_length=500)


class Follow(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='follower', on_delete=models.CASCADE)


class PostTags(models.Model):
    post = models.ForeignKey(Post, related_name='post', on_delete=models.CASCADE)
    tags = models.ForeignKey(Tags, related_name='tags', on_delete=models.CASCADE)


class Like(models.Model):
    like_date = models.DateTimeField(auto_now_add=True)
    user_like = models.ForeignKey(User, related_name='like_user', on_delete=models.CASCADE)
    post_like = models.ForeignKey(Post, related_name='like_post', on_delete=models.CASCADE)

multiclub/forms.py
from django import forms
from .models import *


class CreationPost(forms.ModelForm):
    group = forms.CharField(required=False)
    text = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Post
        fields = ('title', 'text', 'image', 'tags')


class UploadAvatar(forms.ModelForm):
    class Meta:
        model = UserSet
        fields = ('avatar', )

templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}{% if edit == 1 %}Редактирование поста{% else %}Создание поста{% endif %}{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                  {% if edit == 1 %}
                      Редактировать пост
                      {% else %}
                      Новый пост
                  {% endif %}
              </div>
              <div class="card-body">
                  <form method="post" enctype="multipart/form-data" action="{% if edit == 1 %}{% url 'social:update' post.pk %}{% else %}{% url 'social:create' %}{% endif %}">{% csrf_token %}
                      <div class="form-group row my-3 p-3">
                    <label for="id_title">
                      Название поста
                      <span class="required text-danger" >*</span>
                    </label>
                    <textarea name="title" cols="40" rows="1" class="form-control" required id="id_title">{% if edit == 1 %}{{ post.title }}{% endif %}</textarea>
                    <small id="id_text-help" class="form-text text-muted">
                      Название нового поста
                    </small>
                  </div>
                      <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger" >*</span>
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">{% if edit == 1 %}{{ post.text }}{% endif %}</textarea>
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа
                    </label>
                    <select name="group" class="form-control" id="id_group">
                    {% if edit == 1 %}
                        <option value="{{ post.group.id }}" selected>{% if post.group.title %}
                          Группа: {{ post.group.title }}{% else %}---------{% endif %}
                        </option>
                        {% else %}
                        <option value="0" selected>---------
                      </option>
                    {% endif %}
                        {% for item in group %}
                            <option value="{{ item.id }}">Группа: {{ item }}</option>
                        {% endfor %}
                        {% if post.group.title %}
                            <option value="0">---------</option>
                        {% endif %}
                    </select>

                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>

                     <div class="form-group row my-3 p-3">
                        <label for="id_tags">Теги</label>
                        <select name="tags" class="form-control" id="id_tags">
                            {% for item in tags %}
                            <option value="{{ item.id }}">{{ item }}</option>
                            {% endfor %}
                        </select>

                        <small id="id_tags-help" class="form-text text-muted">
                            Выберите один или несколько тегов, которые будут применены к посту
                        </small>
                    </div>


                  <div class="form-group row my-3 p-3">
                  <label for="image">Выберите изображение:</label>
                  <input type="file" name="image" class="form-control" id="image">
                    <small id="id_text-help" class="form-text text-muted">
                      Загрузите изображение
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                                          {% if edit == 1 %}
                      Сохранить
                      {% else %}
                      Создать
                  {% endif %}
                    </button>

                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
        <script>
    // Функция для обновления отображения выбранных тегов
    function updateSelectedTags() {
        var selectedTags = [];
        var select = document.getElementById("id_tags");
        var selectedOptions = select.selectedOptions;

        for (var i = 0; i < selectedOptions.length; i++) {
            selectedTags.push(selectedOptions[i].text);
        }

        var selectedTagsDiv = document.getElementById("selected-tags");
        selectedTagsDiv.innerHTML = "Выбранные теги: " + selectedTags.join(", ");
    }

    // Обработчик изменения элемента select
    document.getElementById("id_tags").addEventListener("change", updateSelectedTags);

    // Инициализация отображения выбранных тегов при загрузке страницы
    window.addEventListener("load", updateSelectedTags);

        $(document).ready(function() {
        $("#id_tags").select2({
            placeholder: "Выберите теги", // Текст для плейсхолдера
            allowClear: true, // Разрешить сброс выбора
            multiple: true // Разрешить множественный выбор
        });
    });

</script>
    </main>
{% endblock content %}

templates/posts/group_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
    <main>
        <div class="container py-5">
            {% if posts %}
                <h1>Все записи группы {{ name }} </h1>
                {% for post in posts %}
                    <ul>
                        <li>
                            <a href="{% url  'social:profile' post.author %} "
                               style="color: black; text-decoration: none">Автор: {{ post.author }}</a>
                        </li>
                        <li>
                            Дата публикации: {{ post.pub_date|date:"d E Y" }}
                        </li>
                    </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <a href="{% url  'social:post_detail' post.pk %} " style="color: black; text-decoration: none;overflow: hidden;text-overflow: ellipsis;max-width: 200px;">
                <img class="card-img my-2" src="{{ im.url }}">
                </a>
          {% endthumbnail %}
                    <span><p><a href="{% url  'social:post_detail' post.pk %} "
                                style="color: black; text-decoration: none">
                                {% if post.text|length > 150 %}
                                    <p>{{ post.text|slice:":150" }}...</p>
                                {% else %}
                                    <p>{{ post.text }}</p>
                                {% endif %}
<!--                        {{ post.text|slice:":200" }}...-->
                    </a></p></span>
                    {% if not forloop.last %}
                        <hr>{% endif %}
                {% endfor %}
            {% else %}
                <h1>У группы {{ name }} пока нет записей(</h1>
            {% endif %}
            {#    <a class="navbar-brand" href="{% url 'posts:group' posts.slug %}">#}
            {#  Перейти на главную#}
            {#</a>#}
            {% include 'includes/paginator.html' %}
        </div>
    </main>
{% endblock content %}
</body>
</html>

templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Главная страница{% endblock %}
{% block content %}
{% load static %}
        <main>
      <div class="container py-5">
          {% include 'includes/switcher.html' %}
  {% for post in posts %}
      <article>
  <ul>
    <li>
      <a href="{% url  'social:profile' post.author %}" style="color: black; text-decoration: none">Автор: {{ post.author }}</a>
    </li>
      {% if post.group.title %}
      <li>
          Группа: {{ post.group.title }}
    </li>
      {% endif %}
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
          {% thumbnail post.image "860x300" crop="center" upscale=True as im %}
            <a href="{% url  'social:post_detail' post.pk %} " style="color: black; text-decoration: none;overflow: hidden;text-overflow: ellipsis;max-width: 200px;">
                <img class="card-img my-2" src="{{ im.url }}">
                </a>
          {% endthumbnail %}
  <span><p><a href="{% url  'social:post_detail' post.pk %} " style="color: black; text-decoration: none;overflow: hidden;text-overflow: ellipsis;max-width: 200px;">
                                      {% if post.text|length > 150 %}
                                    <p>{{ post.text|slice:":150" }}...</p>
                                {% else %}
                                    <p>{{ post.text }}</p>
                                {% endif %}
  </a></p></span>
      {% if post.group.slug %}
        <a href="{% url  'social:group' post.group.slug %}" class="nav-link">все записи группы {{ post.group.title }}</a>
      {% endif %}
      </article>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{#        <a class="navbar-brand" href="{% url 'posts:group' posts.slug %}">#}
{#  Перейти на главную#}
{#</a>#}
            </div>
    </main>
    {% include 'includes/paginator.html' %}
{% endblock content %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ posts.text }}{% endblock %}
{% block content %}
{% load user_filters %}
<main id="site-main">

    <!-- Post Content -->
    <section class="container">
        <article id="post">
            <div class="headings text-center">
                <div class="title">
                        <h2 class="text-title text-dark display-1">{{posts.title}}</h2>
                    </div>
                <div class="meta">
                    <a href="{% url  'social:profile' posts.author.username %}" class="link display-2 text-secondary px-1">
                        <i class="fas fa-user text-primary" style="color: #343a40!important"></i>
                        {{ posts.author.username }}
                    </a>
                    <a href="#" class="link display-2 text-secondary px-1">
                        <i class="fas fa-clock text-primary" style="color: #343a40!important"></i> {{ posts.pub_date|date:"d E Y в H:i" }}
                    </a>
                </div>
            </div>
            {% if posts.image %}
            <div class="thumbnail mt-3">
                {% thumbnail posts.image "960x339" crop="center" upscale=True as im %}
                <img class="thumbnail" src="{{ im.url }}">
                {% endthumbnail %}
            </div>
            {% endif %}
                <div class="content text-dark display-2 secondary-title mt-3">
                    {% if posts.text|length > 150 %}
                    <h5><pre style="white-space: pre-wrap;">{{ posts.text|safe }}</pre></h5>
                    {% else %}
                    <h5 style="text-align: center;"><pre style="white-space: pre-wrap;">{{ posts.text|safe }}</pre></h5>
                    {% endif %}
                </div>
        </article>
        <div class="post-footer mb-3">
            <div class="post-tags d-flex flex-wrap justify-content-center">
                {% for com in tags %}
                <a href="{% url  'social:tag' com.name %}" class="nav-link btn bg-light">{{com.name}}</a>
                {% endfor %}
            </div>
        </div>
        <div class="post-footer mb-3">
            <div class="post-tags d-flex flex-wrap justify-content-center">
            <a href="{% url  'social:like' edit_post %}" class="nav-link">{{ like }} &#10084;</a>
            </div>
        </div>
               <div class="post-comments py-2">
                   <h3 class="text-center">{{comment.count}} Comments</h3>
                   {% for com in comments %}
                    <div class="comment-details">
                        <div class="comment-item py-2">
                            <div class="d-flex">
                                <div class="avatar px-2">
                                {% with user_avatar=avatar|get_user_avatar:com.com_author.id %}
                                    {% if user_avatar %}
                                        <a href="{% url  'social:profile' com.com_author.username %}">
                                            <img src="{{ user_avatar.avatar.url }}" alt="mdo" width="55" height="55" class="rounded-circle">
                                        </a>
                                    {% else %}
                                        <a href="{% url  'social:profile' com.com_author.username %}">
                                            <img src="/media/avatar/unknowuserpic.png" alt="mdo" width="55" height="55" class="rounded-circle">
                                        </a>
                                    {% endif %}
                                {% endwith %}
                                </div>
                                <div class="comment-content">
                                    <h5 class="display-2 m-0">
                                        <strong><a href="{% url  'social:profile' com.com_author.username %}" style="color: black; text-decoration: none"> {{ com.com_author.username }}</a></strong>
                                        {% if request.user.id == com.com_author_id %}
                                        <sup>{{ com.com_date | date:'d.m.Y в H:i'}}	<a href="{% url  'social:com_del' com.id %}" style="color: black; text-decoration: none">&#10006;</a></sup>
                                        {% else %}
                                        <sup>{{ com.com_date | date:'d.m.Y в H:i'}}</sup>
                                        {% endif %}
                                    </h5>
                                    <p class="title-secondary text-dark">
                                         {{ com.com_text }}
                                    </p>

                                </div>
                            </div>
                        </div>
                    </div>
                   {% endfor %}
            <h3 class="text-center display-1 secondary-title py-2">Оставьте комментарий</h3>
                <form method="post" action="{% url 'social:comment' posts.pk %}">{% csrf_token %}
                        <div class="comment-form">
                <textarea class="form-control mt-3" placeholder="Напишите что-нибудь..." rows="10" name="text"></textarea>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary display-2 text-light mt-2">Отправить</button>
                </div>
            </div>
                </form>
        </div>
            </section>
</main>
{% endblock content %}

templates/posts/set_user_profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Настройки{% endblock %}
  {% block content %}
<main>
      <div class="container py-5">
          <div class="d-flex">
                                <div class="comment-content">
                                    <h1>Настройки</h1>
                                </div>
          </div>
                        <div class="container">
                  <a href="{% url  'users:password_change_form' %}" class="nav-link" ><h5>Сменить пароль</h5></a>
                            <a href="#" class="nav-link" ><h5>Сменить email</h5></a>
          <form method="post" enctype="multipart/form-data" action="{% url 'social:settings' request.user %}">
            {% csrf_token %}
              <div class="form-group row my-3 p-3">
                  <h5>Сменить аватар</h5>
                  <label for="avatar">Выберите изображение:</label>
                  <input type="file" name="avatar" class="form-control" id="avatar" accept="image/*">
                    <small id="id_text-help" class="form-text text-muted" >
                      Загрузите изображение
                    </small>
                  </div>
            <div>
                <a href="{% url 'social:del_image' request.user %}">
                <button type="button" class="btn btn-danger" id="deleteButton">
                    Удалить аватар
                </button></a>
                <button type="submit" class="btn btn-primary" id="saveButton" style="display: none;">
                    Сохранить
                </button>
            </div>
        </form>
      </div>
          </div>
    <script src="{% static 'js/js.js' %}"></script>
    </main>
    {% endblock content %}

templates/posts/update_post.html
{% extends 'base.html' %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                  {% if edit == 1 %}
                      Редактировать пост
                      {% else %}
                      Новый пост
                  {% endif %}
              </div>
              <div class="card-body">
                  <form method="post" action="{% url 'social:update' post.pk %}">{% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger" >*</span>
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">{% if edit == 1 %}{{ post.text }}{% endif %}
                    </textarea>
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа
                    </label>
                    <select name="group" class="form-control" id="id_group">
{#                      <option value="" selected>---------</option>#}
                        {% for item in group %}
                            <option value="1">Группа: {{ item.title }}</option>
                        {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                                          {% if edit == 1 %}
                      Добавить
                      {% else %}
                      Сохранить
                  {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock content %}