Magazine/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.views.generic import TemplateView

handler404 = 'multiclub.views.page_not_found'

urlpatterns = [
    path('', include('multiclub.urls')),
    path('group/<slug:slug>/', include('multiclub.urls',namespace='posts2')),
    path("admin/", admin.site.urls),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('',include('api.urls')),
    path(
        'redoc/',
        TemplateView.as_view(template_name='redoc.html'),
        name='redoc'
    ),
    # path('auth/', include('djoser.urls')),
    # path('auth/', include('djoser.urls.jwt')),

]

api/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views as views_token
from rest_framework.routers import SimpleRouter, DefaultRouter
from . import views
from .views import *

app_name = 'api'

router = DefaultRouter()
router.register('posts', PostViewSet, basename='posts')
router.register('group', GroupViewSet, basename='group')
router.register('follow', FollowViewSet, basename='follow')
comments_router = DefaultRouter()
comments_router.register('comments', CommentViewSet, basename='comments')

urlpatterns = [
    path('api/v1/', include('djoser.urls')),
    path('api/v1/', include('djoser.urls.jwt')),
    # path('api/v1/api-token-auth/', views_token.obtain_auth_token),
    path('api/v1/', include(router.urls)),
    path('api/v1/<int:post_id>/', include(comments_router.urls)),

]

multiclub/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import SimpleRouter

from .views import *

app_name = 'social'

urlpatterns = [
    path('', views.index, name='main'),
    path('group/<slug:slug>/',views.group_posts, name='group'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create_post/', views.new_post, name='create'),
    path('posts/<int:post_id>/edit', views.update_post, name='update'),
    path('posts/<int:post_id>/del', views.delete_post, name='delete'),
    path('posts/<int:post_id>/comment', views.comment, name='comment'),
    path('profile/<str:username>/follow', views.follow, name='follow'),
    path('posts/<int:post_id>/like', views.like_post, name='like'),
    path('subscribe/', views.sub, name='sub'),
    path('posts/tags/<str:tag_name>', views.post_tags, name='tag'),
    path('settings/<str:username>/', views.settings_user, name='settings'),
    path('settings/<str:username>/del', views.delete_image, name='del_image'),
    path('comment/<int:com_id>/del', views.delete_com, name='com_del'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

users/urls.py
from django.contrib.auth.views import (
    LogoutView, LoginView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from django.urls import path
from . import views
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done'),
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<slug:uidb64>/<slug:token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

templates/includes/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--    <link rel="stylesheet" href="{% static 'css/style.css' %}">-->
</head>
<body>
               <div class="copyrights">
                   <p class="text-center text-secondary display-2">
                        © {{ year }} <a href="{% url  'social:main' %}" style="color: var(--primary-color);">SocialClub</a> - Personal Blog Theme. All rights reserved.
                   </p>
               </div>
</body>
</html>

templates/includes/header.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gridy Blog</title>
</head>

<body>

<!-- Header -->
<header id="header" class="shadow bg-light">
        <div class="container">
            <nav class="container navbar">
        <a href="{% url  'social:main' %}" class="nav-brand text-dark">
            SocialClub
        </a>
            <ul class="navbar-nav" style="flex-direction: row;">
                {% if user.is_authenticated %}
                {% if edit_post and posts.author == request.user %}
                <a href="{% url 'social:update' edit_post %}" class="nav-link">Редактировать пост</a>
                {% elif edit == 1 %}
                <a href="{% url 'social:delete' post.pk %}" class="nav-link">Удалить пост</a>
                {% else %}
                <a href="{% url 'social:main' %}" class="nav-link">Главная</a>
                <a href="#" class="nav-link">Группы</a>
                {% endif %}
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <div class="dropdown text-end">
        <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
          aria-expanded="false">
            {% if pic %}
            <img src="/media/{{ pic }}"
               alt="mdo" width="35" height="35" class="rounded-circle">
            {% else %}
            <img src="/media/avatar/unknowuserpic.png"
               alt="mdo" width="35" height="35" class="rounded-circle">
            {% endif %}
        </a>
        <ul class="dropdown-menu text-small" style="position: absolute;">
          <li><a class="dropdown-item" href="{% url 'social:profile' user.username %}">Профиль</a></li>
          <li><a class="dropdown-item" href="{% url 'social:settings' user.username %}">Настройки</a></li>
            <li><a class="dropdown-item" href="{% url 'social:create' %}">Создать пост</a></li>
          <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
        </ul>
      </div>
        </div>
                {% else %}
                <a href="{% url 'users:login' %}" class="nav-link">Войти</a>
                <a href="{% url 'users:signup' %}" class="nav-link">Регистрация</a>
                {% endif %}

            </ul>
    </nav>
</header>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>
</body>

</html>

templates/includes/paginator.html
{# templates/posts/includes/paginator.html #}

{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if posts.has_other_pages %}
            <main>
      <div class="container py-5">
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if posts.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
        {% if posts.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
                </div>
    </main>
{% endif %}

templates/includes/switcher.html
{% load static %}
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a style="color: black; text-decoration: none"
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'social:main' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a style="color: black; text-decoration: none"
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'social:sub' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}